package cn.tuyucheng.taketoday.mongodb;

import cn.tuyucheng.taketoday.mongodb.daos.UserRepository;
import cn.tuyucheng.taketoday.mongodb.models.User;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.assertj.core.api.Assertions.assertThat;


@ExtendWith(SpringExtension.class)
@SpringBootTest
@DirtiesContext
class MongoDbAutoGeneratedFieldIntegrationTest {

	@Autowired
	UserRepository userRepository;

	@Test
	void contextLoads() {
	}

	@Test
	void givenUserObject_whenSave_thenCreateNewUser() {
		User user = new User();
		user.setFirstName("John");
		user.setLastName("Doe");
		user.setEmail("john.doe@example.com");
		userRepository.save(user);

		assertThat(userRepository.findAll().size()).isGreaterThan(0);
	}
}